-- =============================================================
--  DataHub — Supabase schema
-- =============================================================
--  This starter uses one Postgres table per `TableConfig` entry
--  declared in `app/lib/config.ts`.
--
--  The DB table name can differ from the config id. Example:
--  - `TableConfig.id     = "items"`  (URL slug, used in /api/items)
--  - `TableConfig.tableName = "products"`  (real Postgres table)
--
--  Every table needs the same 4 RLS policies shown below, all
--  scoped to `auth.uid() = user_id` for per-user isolation.
--
--  To add a new entity:
--    1. Append a `TableConfig` to `appConfig.tables` in
--       `app/lib/config.ts` (with a unique `id` + matching
--       `tableName`).
--    2. Copy the commented `reviews` example at the bottom of
--       this file, uncomment it, rename the table and columns.
--    3. Paste into the Supabase SQL editor.
-- =============================================================

create table if not exists products (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  price numeric not null default 0,
  quantity integer not null default 0,
  category text not null default 'General',
  status text not null default 'Active',
  created_at timestamp with time zone not null default now()
);

-- If you already ran the previous version of this schema, add the
-- status column with this one-liner instead of re-creating the table:
--   alter table products add column status text not null default 'Active';

alter table products enable row level security;

create policy "Users can view own products"
on products for select
using (auth.uid() = user_id);

create policy "Users can insert own products"
on products for insert
with check (auth.uid() = user_id);

create policy "Users can update own products"
on products for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can delete own products"
on products for delete
using (auth.uid() = user_id);

-- Enable Realtime so the dashboard can subscribe to live changes
-- (insert / update / delete events stream to the browser).
-- Run this once per table you want to sync live.
alter publication supabase_realtime add table products;


-- =============================================================
--  EXAMPLE — second table for a marketplace-style problem.
--  Uncomment + adapt to add a new entity to your app.
-- =============================================================
--
-- create table if not exists reviews (
--   id bigint generated by default as identity primary key,
--   user_id uuid not null references auth.users(id) on delete cascade,
--   item_id bigint not null,
--   rating integer not null check (rating between 1 and 5),
--   comment text not null default '',
--   created_at timestamp with time zone not null default now()
-- );
--
-- alter table reviews enable row level security;
--
-- create policy "Users can view own reviews"
-- on reviews for select using (auth.uid() = user_id);
--
-- create policy "Users can insert own reviews"
-- on reviews for insert with check (auth.uid() = user_id);
--
-- create policy "Users can update own reviews"
-- on reviews for update
-- using (auth.uid() = user_id)
-- with check (auth.uid() = user_id);
--
-- create policy "Users can delete own reviews"
-- on reviews for delete using (auth.uid() = user_id);
--
-- Then in `app/lib/config.ts`:
--   tables: [ITEMS_TABLE, REVIEWS_TABLE]
-- where REVIEWS_TABLE matches the schema above (id, item_id,
-- rating, comment, user_id).
