create table if not exists products (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  price numeric not null default 0,
  quantity integer not null default 0,
  category text not null default 'General',
  created_at timestamp with time zone not null default now()
);

alter table products enable row level security;

create policy "Users can view own products"
on products for select
using (auth.uid() = user_id);

create policy "Users can insert own products"
on products for insert
with check (auth.uid() = user_id);

create policy "Users can update own products"
on products for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can delete own products"
on products for delete
using (auth.uid() = user_id);
