-- =============================================================
--  DataHub — Supabase schema
-- =============================================================
--  This starter uses one Postgres table per `TableConfig` entry
--  declared in `app/lib/config.ts`.
--
--  The DB table name can differ from the config id. Example:
--  - `TableConfig.id     = "items"`  (URL slug, used in /api/items)
--  - `TableConfig.tableName = "products"`  (real Postgres table)
--
--  Every table needs the same 4 RLS policies shown below, all
--  scoped to `auth.uid() = user_id` for per-user isolation.
--
--  To add a new entity:
--    1. Append a `TableConfig` to `appConfig.tables` in
--       `app/lib/config.ts` (with a unique `id` + matching
--       `tableName`).
--    2. Copy the commented `reviews` example at the bottom of
--       this file, uncomment it, rename the table and columns.
--    3. Paste into the Supabase SQL editor.
-- =============================================================

create table if not exists products (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  price numeric not null default 0,
  quantity integer not null default 0,
  category text not null default 'General',
  status text not null default 'Active',
  created_at timestamp with time zone not null default now()
);

-- =============================================================
--  User profiles + RBAC
-- =============================================================
--  Every auth.users row gets a corresponding profiles row with a
--  `role`. Sign-ups default to 'user'. Promote a user to 'admin'
--  with a manual UPDATE — never expose that to the client.
-- =============================================================

create table if not exists profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'user' check (role in ('admin', 'user')),
  created_at timestamp with time zone not null default now()
);

alter table profiles enable row level security;

create policy "Users can read own profile"
on profiles for select
using (auth.uid() = user_id);

-- The trigger below handles inserts (so we never need an INSERT
-- policy). Updates are restricted to admins via a separate policy.

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (user_id, role)
  values (new.id, 'user')
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

-- Admin-only UPDATE policy. Replace <admin-user-id> with your
-- actual auth.users.id to bootstrap the first admin. The trigger
-- default is always 'user'.
-- create policy "Admins can update profiles"
-- on profiles for update
-- using (
--   exists (
--     select 1 from public.profiles p
--     where p.user_id = auth.uid() and p.role = 'admin'
--   )
-- );

-- =============================================================
--  Bootstrap admin (demo creds)
-- =============================================================
--  After signing up with kori@dev.com / 1234, run this once to
--  promote that account to admin so the demo can use destructive
--  actions. Replace the email if you used a different one.
-- =============================================================
-- update profiles
-- set role = 'admin'
-- where user_id = (select id from auth.users where email = 'kori@dev.com');

-- If you already ran the previous version of this schema, add the
-- status column with this one-liner instead of re-creating the table:
--   alter table products add column status text not null default 'Active';

alter table products enable row level security;

create policy "Users can view own products"
on products for select
using (auth.uid() = user_id);

create policy "Users can insert own products"
on products for insert
with check (auth.uid() = user_id);

create policy "Users can update own products"
on products for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can delete own products"
on products for delete
using (auth.uid() = user_id);

-- Enable Realtime so the dashboard can subscribe to live changes
-- (insert / update / delete events stream to the browser).
-- Run this once per table you want to sync live.
alter publication supabase_realtime add table products;


-- =============================================================
--  File uploads — single shared "uploads" bucket.
--  Run this in the Supabase SQL editor AFTER creating the
--  bucket (Storage -> New bucket -> name: "uploads" -> public).
--  The path convention is <user_id>/<table_id>/<file> so the
--  RLS policies below scope every operation to the owner.
-- =============================================================
--
-- insert into storage.buckets (id, name, public)
-- values ('uploads', 'uploads', true)
-- on conflict (id) do nothing;
--
-- create policy "Users can upload to own folder"
-- on storage.objects for insert
-- with check (
--   bucket_id = 'uploads'
--   and auth.uid()::text = (storage.foldername(name))[1]
-- );
--
-- create policy "Users can update own uploads"
-- on storage.objects for update
-- using (
--   bucket_id = 'uploads'
--   and auth.uid()::text = (storage.foldername(name))[1]
-- );
--
-- create policy "Users can delete own uploads"
-- on storage.objects for delete
-- using (
--   bucket_id = 'uploads'
--   and auth.uid()::text = (storage.foldername(name))[1]
-- );
--
-- Public reads are automatic because the bucket is public. To
-- restrict reads to owners, add:
--   create policy "Users can read own uploads"
--   on storage.objects for select
--   using (
--     bucket_id = 'uploads'
--     and auth.uid()::text = (storage.foldername(name))[1]
--   );
-- and toggle the bucket to private in the Supabase dashboard.


-- =============================================================
--  EXAMPLE — second table for a marketplace-style problem.
--  Uncomment + adapt to add a new entity to your app.
-- =============================================================
--
-- create table if not exists reviews (
--   id bigint generated by default as identity primary key,
--   user_id uuid not null references auth.users(id) on delete cascade,
--   item_id bigint not null,
--   rating integer not null check (rating between 1 and 5),
--   comment text not null default '',
--   created_at timestamp with time zone not null default now()
-- );
--
-- alter table reviews enable row level security;
--
-- create policy "Users can view own reviews"
-- on reviews for select using (auth.uid() = user_id);
--
-- create policy "Users can insert own reviews"
-- on reviews for insert with check (auth.uid() = user_id);
--
-- create policy "Users can update own reviews"
-- on reviews for update
-- using (auth.uid() = user_id)
-- with check (auth.uid() = user_id);
--
-- create policy "Users can delete own reviews"
-- on reviews for delete using (auth.uid() = user_id);
--
-- Then in `app/lib/config.ts`:
--   tables: [ITEMS_TABLE, REVIEWS_TABLE]
-- where REVIEWS_TABLE matches the schema above (id, item_id,
-- rating, comment, user_id).
